### ISSUE TITLE
How to include hidden columns from the Socrata dataset

### ISSUE THREAD

**Issue by chursaner** [interworks-morr/wdc-socrata#1]
Hi Matthew,

Great work on this connector!! We on the LA open data team are so appreciative.

My issue is that I need to connect to the hidden columns from my Socrata dataset, but only the visible ones show up in the WDC.

For more background, [this dataset](https://data.lacity.org/A-Livable-and-Sustainable-City/Total-and-Affordable-Housing-Units/rckt-8prm?category=A-Livable-and-Sustainable-City&view_name=Total-and-Affordable-Housing-Units) has a hidden column with fake dates that I created in order for Tableau to show fiscal quarters (i.e. Fiscal Q1 is in July but the hidden date column says 1/1).  [Here](https://public.tableau.com/profile/chelsea.ursaner#!/vizhome/TotalHousingCombinedCharts2/TotalHousing) is a rough idea of the viz.

Thank you!
Chelsea
chelsea dot ursaner at lacity dot org

**Comment by interworks-morr** [comment]
The schema fetch process is using a "$select=*" query in an attempt to get all of the columns.  Admittedly, I'm not a Socrata expert, but I have not found anything in the documentation yet that will make it include the hidden columns.
